# Front-end Deployment (Apache)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-frontend
spec:
  selector:
    matchLabels:
      app: apache-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: apache-frontend
    spec:
      containers:
      - name: apache
        image: httpd:latest  # Correção: "httpd" é a imagem correta
        ports:
        - containerPort: 80

---
# Front-end Service
apiVersion: v1
kind: Service
metadata:
  name: apache-frontend-service
spec:
  selector:
    app: apache-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Back-end Deployment (MongoDB)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-backend
spec:
  selector:
    matchLabels:
      app: mongo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-backend
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: mydatabase
        - name: MONGO_INITDB_ROOT_USERNAME
          value: myuser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mypassword

---
# Back-end Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-backend-service
spec:
  selector:
    app: mongo-backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
